### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by AmingWu** [zwq456/CLIP-VIS#1]
Dear Authors,

How long does your method need to train?

**Comment by SCYF123** [comment]
We trained our method with resnet50 backbone on four NVIDIA GeForce RTX 3090 GPUs for two days and nine hours.

**Comment by AmingWu** [comment]
Thanks. Do you perform training on the work [7] (Towards open-vocabulary video instance segmentation)? If you train, how long does it take?

**Comment by SCYF123** [comment]
Sorry, we haven't trained work[7] completely.
