### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by SuleBai** [zwq456/CLIP-VIS#2]
Hi, thanks for your great work.

When I use the config `configs/clipvis_ConvNeXt-B.yaml`, there is an error below.

```
RuntimeError: Pretrained weights (laion2b_s29b_b131k_ft_soup) not found for model convnext_base_w_320.
Available pretrained tags (['laion_aesthetic_s13b_b82k', 'laion_aesthetic_s13b_b82k_augreg'].
```

And I check on the openclip website(https://github.com/mlfoundations/open_clip/blob/main/docs/openclip_results.csv), it seems the `laion2b_s29b_b131k_ft_soup` is not valid for the `convnext_base_w_320`.

Besides, is the checkpoint for the setting trained on `COCO and YTVIS2019` available?

**Comment by SCYF123** [comment]
I'm sorry for this mistake. The pretrained weights is `laion_aesthetic_s13b_b82k`.

**Comment by SuleBai** [comment]
Thanks for your reply. Besides, is the checkpoint for the setting trained on COCO and YTVIS2019 available?

**Comment by SCYF123** [comment]
Hi, @SuleBai 
I have update the `Readme` file, please check it for checkpoint.

**Comment by SuleBai** [comment]
Thanks for your reply.
